import type { Wallpaper } from './types';

export const wallpapers: Wallpaper[] = [
  {
    id: 1,
    className: 'bg-tile-1',
    name: 'under.net',
    author: 'under.net',
    authorUrl: 'https://soundcloud.com/underdotnet',
    previewImage: 'https://dwc71k9eqn.ufs.sh/f/JxylFZcO3S9kMf7ty6cZ5xnodGOP6XrA4pkfJsWlwZvtDQhy',
  },
  {
    id: 2,
    className: 'bg-tile-2',
    name: 'Blue Cube',
    author: 'under.net',
    authorUrl: 'https://soundcloud.com/underdotnet',
    previewImage: 'https://dwc71k9eqn.ufs.sh/f/JxylFZcO3S9k3HnhLlvGfEp0rICdqH1lvQBi4NFtos39wZeD',
    darkBackground: true,
  },
  {
    id: 3,
    className: 'bg-tile-3',
    name: 'Cenobia Bassline 2',
    author: 'under.net',
    authorUrl: 'https://soundcloud.com/underdotnet',
    previewImage: 'https://dwc71k9eqn.ufs.sh/f/JxylFZcO3S9kvOMZSK6Ty6w9FAxjPaeqoRcSXln0BCuEIp2D',
    darkBackground: true,
  },
  {
    id: 4,
    className: 'bg-tile-4',
    name: 'Cenobia Bassline Grad 1',
    author: 'under.net',
    authorUrl: 'https://soundcloud.com/underdotnet',
    previewImage: 'https://dwc71k9eqn.ufs.sh/f/JxylFZcO3S9kREAdlFuwMajqye4v8CuoWVhPdriscZH7DS9b',
    darkBackground: true,
  },
  {
    id: 5,
    className: 'bg-tile-5',
    name: 'Picsart 24-07-31 17-34-57-343',
    author: 'under.net',
    authorUrl: 'https://soundcloud.com/underdotnet',
    previewImage: 'https://dwc71k9eqn.ufs.sh/f/JxylFZcO3S9k3Gp6cKKvGfEp0rICdqH1lvQBi4NFtos39wZe',
    darkBackground: true,
  },
  {
    id: 6,
    className: 'bg-tile-6',
    name: 'Shapes',
    author: 'under.net',
    authorUrl: 'https://soundcloud.com/underdotnet',
    previewImage: 'https://dwc71k9eqn.ufs.sh/f/JxylFZcO3S9k41luTA9ZOzpPV5duFwJI7LQTCRfGnHxK1Elo',
  },
  {
    id: 7,
    className: 'bg-tile-7',
    name: 'Enable Fiber',
    author: 'under.net',
    authorUrl: 'https://soundcloud.com/underdotnet',
    previewImage: 'https://dwc71k9eqn.ufs.sh/f/JxylFZcO3S9k4tmbLw9ZOzpPV5duFwJI7LQTCRfGnHxK1Elo',
  },
  {
    id: 8,
    className: 'bg-tile-8',
    name: 'Obama Wallframe 1',
    author: 'tacard',
    previewImage: 'https://dwc71k9eqn.ufs.sh/f/JxylFZcO3S9kRpNetzNuwMajqye4v8CuoWVhPdriscZH7DS9',
    darkBackground: true,
  },
  {
    id: 9,
    className: 'bg-tile-9',
    name: 'Stone',
    author: 'Minecraft',
    previewImage: 'https://dwc71k9eqn.ufs.sh/f/JxylFZcO3S9kvBnFFE6Ty6w9FAxjPaeqoRcSXln0BCuEIp2D',
  },
];
